### ISSUE TITLE
共有ボタンを作成する

### ISSUE THREAD

**Issue by AtiR-peni** [hanzawayuki/Gteam#17]
## 概要 (Summary):
他サイトやアプリなどに共有するアイコン
## 誰が使うか (For whom):
- [ ] ユーザー

## 何のために (For what):
使いやすさと戻りたいときに戻るため

**Comment by hanzawayuki** [comment]
・SNSの共有ボタン
　LINE、Twitter、Facebook等のボタンを結果画面に配置
